// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PPG.CharacterSheets.Characters.Entities;
using PPG.CharacterSheets.Store;

namespace PPG.CharacterSheets.Migrations
{
    [DbContext(typeof(Context<Character>))]
    [Migration("20180523152357_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("PPG.CharacterSheets.Characters.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CharacterName");

                    b.Property<int>("Experience");

                    b.Property<string>("MetaData");

                    b.Property<int>("RuleSet");

                    b.Property<string>("Stats");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
