// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using PPG.CharacterSheets._RuleSets;
using PPG.CharacterSheets.Store;
using System;

namespace PPG.CharacterSheets.Migrations
{
    [DbContext(typeof(MigrationContext))]
    partial class MigrationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("PPG.CharacterSheets.Characters.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abilities");

                    b.Property<string>("CharacterName");

                    b.Property<string>("Classes");

                    b.Property<string>("MetaData");

                    b.Property<int>("RuleSet");

                    b.Property<string>("Skills");

                    b.Property<string>("Stats");

                    b.Property<string>("Wallets");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("PPG.CharacterSheets.RuleSets.Entities.RuleSetInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreateCharacterPath");

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<int>("RuleSet");

                    b.Property<string>("ViewCharacterPath");

                    b.HasKey("Id");

                    b.ToTable("RuleSets");
                });
#pragma warning restore 612, 618
        }
    }
}
